project:
  type: book
  output-dir: docs

book:
  title: "livror"
  author: "Robin Kohrs"
  date: "9/07/2022"
  toc: true
  toc-depth: 3
  chapters:
    - index.qmd
    - intro.qmd
    - datatypes.qmd
    - dplyr.qmd
    - mapping.qmd
    - ggplot.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


