project:
  type: book
  output-dir: docs

book:
  title: "Make my life easy with R"
  author: "Robin Kohrs"
  date: "9/07/2022"
  chapters:
    - index.qmd
    - datatypes.qmd
    - dplyr.qmd
    - ggplot.qmd
    - sf.qmd
    - stars.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    code-fold: true
  pdf:
    documentclass: scrreprt


